import json

# Comprehensive Real Cities Master Dictionary for 197 Countries
# Each list contains tuples: (cityName, stateOrRegion, population, cityType, isCapital, focus)

FACTUAL_WORLD_CITIES = {
    "US": [
        ("New York City", "New York", 8335897, "Financial Hub", False, "Global Banking, Media, Technology & Corporate HQ"),
        ("Los Angeles", "California", 3822238, "Tech Hub", False, "Entertainment, Media, Tech & Aerospace"),
        ("Chicago", "Illinois", 2665039, "Industrial & Port", False, "Financial Derivatives, Logistics & Manufacturing"),
        ("Houston", "Texas", 2302878, "Industrial & Port", False, "Energy & Oil Processing, Aerospace & Medical Research"),
        ("Phoenix", "Arizona", 1644409, "Regional Center", False, "Semiconductor Manufacturing, Finance & Healthcare"),
        ("Philadelphia", "Pennsylvania", 1567258, "Regional Center", False, "Healthcare, Higher Education, Biotech & Financial Services"),
        ("San Antonio", "Texas", 1472909, "Regional Center", False, "Military Defense, Cybersecurity & Healthcare"),
        ("San Diego", "California", 1381162, "Tech Hub", False, "Biotechnology, Defense Electronics & Wireless Tech"),
        ("Dallas", "Texas", 1304379, "Financial Hub", False, "Telecommunications, Banking & Supply Chain Logistics"),
        ("San Jose", "California", 1013240, "Tech Hub", False, "Silicon Valley Software Engineering & Hardware Innovation"),
        ("Austin", "Texas", 974117, "Tech Hub", False, "Software Development, AI Research & Semiconductor Design"),
        ("Jacksonville", "Florida", 971319, "Industrial & Port", False, "Maritime Logistics, Banking & Healthcare Services"),
        ("Fort Worth", "Texas", 956709, "Industrial & Port", False, "Aerospace Manufacturing, Rail Logistics & Defense"),
        ("Columbus", "Ohio", 907971, "Regional Center", False, "Retail Corporate HQ, E-Commerce Logistics & Education"),
        ("Indianapolis", "Indiana", 880621, "Regional Center", False, "Pharmaceuticals, Auto Racing Tech & Freight Logistics"),
        ("Charlotte", "North Carolina", 897588, "Financial Hub", False, "Commercial Banking, Energy & Fintech Services"),
        ("San Francisco", "California", 808437, "Tech Hub", False, "Venture Capital, Cloud Software & Artificial Intelligence"),
        ("Seattle", "Washington", 749256, "Tech Hub", False, "Cloud Computing, E-Commerce, Aerospace & Biotech"),
        ("Denver", "Colorado", 713252, "Regional Center", False, "Telecommunications, Aerospace & Renewable Energy"),
        ("Oklahoma City", "Oklahoma", 681054, "Regional Center", False, "Energy Exploration, Aviation & Logistics"),
        ("Nashville", "Tennessee", 683622, "Regional Center", False, "Healthcare Management, Music Industry & Automotive"),
        ("El Paso", "Texas", 677456, "Industrial & Port", False, "Cross-Border Trade, Electronics Assembly & Logistics"),
        ("Washington", "District of Columbia", 671803, "Capital", True, "Government Administration, Defense, Policy & Public Sector"),
        ("Las Vegas", "Nevada", 656274, "Regional Center", False, "Hospitality Management, Gaming Tech & Conventions"),
        ("Boston", "Massachusetts", 650706, "Tech Hub", False, "Biotech Research, Higher Education, Asset Management"),
        ("Portland", "Oregon", 635067, "Tech Hub", False, "Athletic Footwear Design, Clean Tech & Semiconductor FABs"),
        ("Louisville", "Kentucky", 624444, "Industrial & Port", False, "Air Cargo Logistics (UPS Worldport) & Manufacturing"),
        ("Memphis", "Tennessee", 621056, "Industrial & Port", False, "Global Express Logistics (FedEx Hub) & Agribusiness"),
        ("Detroit", "Michigan", 620376, "Industrial & Port", False, "Automotive Engineering, Electric Vehicles & Advanced Mfg"),
        ("Baltimore", "Maryland", 569931, "Industrial & Port", False, "Maritime Port Operations, Healthcare & Cybersecurity"),
        ("Milwaukee", "Wisconsin", 563305, "Industrial & Port", False, "Industrial Automation, Water Tech & Precision Machinery"),
        ("Albuquerque", "New Mexico", 560274, "Tech Hub", False, "National Laboratories, Directed Energy & Solar Tech"),
        ("Fresno", "California", 545567, "Regional Center", False, "Agribusiness, Food Processing & Irrigation Tech"),
        ("Tucson", "Arizona", 546574, "Tech Hub", False, "Optics & Photonics, Defense Missiles & Mining Tech"),
        ("Sacramento", "California", 524943, "Regional Center", False, "State Government, Clean Energy & Agricultural Tech"),
        ("Mesa", "Arizona", 504258, "Regional Center", False, "Aerospace Manufacturing, Education & Medical Tech"),
        ("Kansas City", "Missouri", 508090, "Regional Center", False, "Rail Freight Transportation, Animal Health & Engineering"),
        ("Atlanta", "Georgia", 498715, "Financial Hub", False, "Fintech, Telecommunications, Airline Hub & Logistics"),
        ("Omaha", "Nebraska", 486051, "Financial Hub", False, "Insurance, Agribusiness, Railroad Logistics & Finance"),
        ("Colorado Springs", "Colorado", 478961, "Tech Hub", False, "Cybersecurity, Space Command Defense & Optics"),
        ("Raleigh", "North Carolina", 467592, "Tech Hub", False, "Research Triangle Software, Life Sciences & AI"),
        ("Long Beach", "California", 466742, "Industrial & Port", False, "Container Port Operations, Commercial Aviation & Energy"),
        ("Virginia Beach", "Virginia", 459470, "Regional Center", False, "Naval Defense, Subsea Fiber Cables & Tourism"),
        ("Miami", "Florida", 442241, "Financial Hub", False, "Latin American Trade, Wealth Management & Real Estate"),
        ("Oakland", "California", 440646, "Industrial & Port", False, "Container Shipping Terminal, Clean Tech & Green Energy"),
        ("Minneapolis", "Minnesota", 429954, "Regional Center", False, "Medical Devices, Retail HQ & Food Processing"),
        ("Tulsa", "Oklahoma", 413066, "Regional Center", False, "Aviation Maintenance, Energy Trading & Cyber Tech"),
        ("Bakersfield", "California", 403455, "Industrial & Port", False, "Petroleum Extraction, Agribusiness & Logistics"),
        ("Tampa", "Florida", 387050, "Financial Hub", False, "Financial Back-Office, Cybersecurity & Defense Tech"),
        ("Arlington", "Texas", 394266, "Industrial & Port", False, "Automotive Assembly, Sports Management & Aerospace")
    ],
    "GB": [
        ("London", "Greater London", 8982000, "Capital", True, "Global Finance, Fintech, Creative Media & Tech"),
        ("Birmingham", "West Midlands", 1149000, "Industrial & Port", False, "Advanced Engineering, Automotive & Financial Services"),
        ("Glasgow", "Scotland", 635640, "Regional Center", False, "Shipbuilding, Satellite Tech & Renewable Energy"),
        ("Manchester", "North West", 553230, "Tech Hub", False, "Digital Media, E-Commerce, Software & Graphene Research"),
        ("Liverpool", "North West", 498042, "Industrial & Port", False, "Maritime Port, Life Sciences & Automotive Manufacturing"),
        ("Bristol", "South West", 472400, "Tech Hub", False, "Aerospace Engineering, Microelectronics & Robotics"),
        ("Edinburgh", "Scotland", 527620, "Financial Hub", False, "Asset Management, Banking, AI Research & Life Sciences"),
        ("Sheffield", "Yorkshire", 584853, "Industrial & Port", False, "Advanced Manufacturing, Precision Steel & Health Tech"),
        ("Leicester", "East Midlands", 368600, "Regional Center", False, "Textiles, Food Manufacturing & Space Science"),
        ("Coventry", "West Midlands", 345300, "Industrial & Port", False, "Electric Vehicle Design, Battery Tech & Automotive"),
        ("Bradford", "Yorkshire", 539700, "Regional Center", False, "Chemicals, Engineering, Textiles & E-Commerce"),
        ("Cardiff", "Wales", 366900, "Regional Center", False, "Financial Technology, Media Production & Life Sciences"),
        ("Belfast", "Northern Ireland", 343542, "Tech Hub", False, "Cybersecurity, Financial Services & Aerospace"),
        ("Nottingham", "East Midlands", 331100, "Tech Hub", False, "Pharmaceuticals, Clean Tech & Software Development"),
        ("Kingston upon Hull", "Yorkshire", 259700, "Industrial & Port", False, "Offshore Wind Energy, Chemicals & Maritime Logistics"),
        ("Newcastle upon Tyne", "North East", 300100, "Tech Hub", False, "Subsea Offshore Engineering, Gaming Tech & Software"),
        ("Stoke-on-Trent", "West Midlands", 256300, "Industrial & Port", False, "Advanced Ceramics, Logistics & Manufacturing"),
        ("Southampton", "South East", 252522, "Industrial & Port", False, "Deep-Sea Container Port, Marine Science & Cruise Hub"),
        ("Derby", "East Midlands", 258700, "Industrial & Port", False, "Rolls-Royce Aerospace, Rail Engineering & Power Systems"),
        ("Portsmouth", "South East", 208100, "Industrial & Port", False, "Naval Defense Engineering, Maritime Tech & Logistics"),
        ("Plymouth", "South West", 264200, "Industrial & Port", False, "Marine Technology, Naval Defense & Oceanography"),
        ("Northampton", "East Midlands", 225100, "Regional Center", False, "Logistics, Distribution Centers & Footwear Tech"),
        ("Reading", "South East", 174200, "Tech Hub", False, "Enterprise Software (Oracle, Microsoft), IT & Telecom"),
        ("Aberdeen", "Scotland", 229060, "Industrial & Port", False, "Subsea Energy Technology, Offshore Oil & Renewables"),
        ("Wolverhampton", "West Midlands", 263700, "Industrial & Port", False, "Aerospace Components, Engineering & Metal Fabrication"),
        ("Dundee", "Scotland", 148820, "Tech Hub", False, "Video Games Development, Life Sciences & Digital Media"),
        ("Luton", "East Midlands", 213500, "Industrial & Port", False, "Aviation Services, Airport Logistics & Automotive"),
        ("Swindon", "South West", 222200, "Industrial & Port", False, "Automotive Manufacturing, Pharmaceuticals & Insurance"),
        ("Warrington", "North West", 210000, "Tech Hub", False, "Nuclear Engineering, Power Services & Distribution"),
        ("York", "Yorkshire", 211000, "Regional Center", False, "Rail Technology, Agri-Tech, Biotechnology & Tourism"),
        ("Cambridge", "East of England", 145700, "Tech Hub", False, "Silicon Fen Biotech, AI Research & Semiconductor Design"),
        ("Oxford", "South East", 152400, "Tech Hub", False, "Life Sciences, Electric Vehicle R&D & Publishing"),
        ("Norwich", "East of England", 143100, "Regional Center", False, "Agri-Tech, Food Research, Insurance & Financial Services"),
        ("Exeter", "South West", 130700, "Regional Center", False, "Climate Data Analytics (Met Office) & FinTech"),
        ("Gloucester", "South West", 129100, "Regional Center", False, "Aviation Engineering, Nuclear Services & Insurance"),
        ("Ipswich", "East of England", 136900, "Industrial & Port", False, "Telecommunications R&D (Adastral Park) & Port Logistics"),
        ("Preston", "North West", 141800, "Industrial & Port", False, "BAE Systems Military Aircraft Manufacturing & Defense"),
        ("Sunderland", "North East", 277400, "Industrial & Port", False, "Nissan Automotive Plant, EV Battery Manufacturing"),
        ("Milton Keynes", "South East", 287000, "Tech Hub", False, "Logistics Automation, FinTech & Robotics Testing"),
        ("Swansea", "Wales", 247000, "Industrial & Port", False, "Subsea Tech, Metal Processing & Healthcare Research"),
        ("Peterborough", "East of England", 202000, "Regional Center", False, "E-Commerce Distribution, Agri-Food & Environmental Tech"),
        ("Blackpool", "North West", 139000, "Regional Center", False, "Tourism, Civil Service Administration & Aviation"),
        ("Bournemouth", "South West", 194000, "Financial Hub", False, "Financial Back-Office Services, Digital Media & Education"),
        ("Middlesbrough", "North East", 140000, "Industrial & Port", False, "Chemical Processing, Offshore Energy & Steel Fabrication"),
        ("Bolton", "North West", 285000, "Industrial & Port", False, "Manufacturing, Logistics & Healthcare Distribution"),
        ("Stockport", "North West", 293000, "Regional Center", False, "Financial Services, Digital Marketing & Manufacturing"),
        ("Colchester", "East of England", 192000, "Regional Center", False, "Military Garrison, Digital Tech & Educational Hub"),
        ("Telford", "West Midlands", 175000, "Industrial & Port", False, "Robotics Manufacturing, Automotive Plastics & Defense"),
        ("Huddersfield", "Yorkshire", 162000, "Industrial & Port", False, "Chemical Manufacturing, Textiles & Precision Engineering"),
        ("Brighton", "South East", 290000, "Tech Hub", False, "Silicon Beach Digital Media, Game Dev & Creative Industries")
    ],
    "CA": [
        ("Toronto", "Ontario", 2794356, "Financial Hub", False, "Global Banking, Artificial Intelligence, FinTech & Media"),
        ("Montreal", "Quebec", 1762949, "Tech Hub", False, "AI Research, Video Game Development, Aerospace & BioTech"),
        ("Calgary", "Alberta", 1306784, "Industrial & Port", False, "Clean Energy, Oil & Gas HQ, Logistics & Financial Tech"),
        ("Ottawa", "Ontario", 1017449, "Capital", True, "Government Administration, Software Tech & Defense R&D"),
        ("Edmonton", "Alberta", 1010899, "Industrial & Port", False, "Petrochemical Refining, AI Research & Construction"),
        ("Winnipeg", "Manitoba", 749607, "Regional Center", False, "Agribusiness, Heavy Manufacturing, Aerospace & Transportation"),
        ("Vancouver", "British Columbia", 662248, "Tech Hub", False, "Software Development, Visual Effects, Clean Tech & Maritime Port"),
        ("Quebec City", "Quebec", 549459, "Regional Center", False, "Public Administration, Optics/Photonics, Bio-Health & Video Games"),
        ("Hamilton", "Ontario", 569353, "Industrial & Port", False, "Advanced Steel Manufacturing, Medical Sciences & Freight Port"),
        ("Kitchener", "Ontario", 256885, "Tech Hub", False, "Waterloo Tech Corridor Software, Robotics & FinTech"),
        ("London", "Ontario", 422324, "Regional Center", False, "Healthcare Research, Defense Vehicles, Insurance & Education"),
        ("Victoria", "British Columbia", 91867, "Regional Center", False, "Provincial Administration, Tech Startups & Marine Research"),
        ("Halifax", "Nova Scotia", 439819, "Industrial & Port", False, "Atlantic Maritime Logistics, Ocean Tech, Naval Defense & Finance"),
        ("Oshawa", "Ontario", 166000, "Industrial & Port", False, "Automotive Assembly (GM), Clean Energy & Logistics"),
        ("Windsor", "Ontario", 229660, "Industrial & Port", False, "Cross-Border Automotive Manufacturing & Electric Batteries"),
        ("Saskatoon", "Saskatchewan", 266141, "Regional Center", False, "Potash Mining Tech, Agribusiness Research & Bio-Science"),
        ("Regina", "Saskatchewan", 226404, "Regional Center", False, "Agricultural Grain Exports, Steel Manufacturing & Energy"),
        ("St. Catharines", "Ontario", 136803, "Regional Center", False, "Agri-Tech, Wine Production, Logistics & Advanced Mfg"),
        ("Barrie", "Ontario", 147829, "Regional Center", False, "Automotive Parts, Health Tech & Construction Services"),
        ("Kelowna", "British Columbia", 142127, "Tech Hub", False, "Okanagan Tech Hub, Agribusiness & Digital Media"),
        ("Abbotsford", "British Columbia", 153524, "Industrial & Port", False, "Agribusiness Processing, Aerospace Services & Freight Logistics"),
        ("Sudbury", "Ontario", 166000, "Industrial & Port", False, "Mining Innovation, Nickel/Copper Processing & Clean Tech"),
        ("Kingston", "Ontario", 132410, "Regional Center", False, "Higher Education, Health Sciences, Defense & Green Tech"),
        ("Saguenay", "Quebec", 144746, "Industrial & Port", False, "Aluminum Smelting, Forestry & Hydroelectric Energy"),
        ("Sherbrooke", "Quebec", 172950, "Tech Hub", False, "Quantum Computing, Microelectronics & Life Sciences"),
        ("Trois-Rivières", "Quebec", 139163, "Industrial & Port", False, "Pulp and Paper, Metals Processing & Innovation Hub"),
        ("Guelph", "Ontario", 135113, "Tech Hub", False, "Agri-Food Bio-Technology, Environmental Engineering & IT"),
        ("Moncton", "New Brunswick", 71889, "Regional Center", False, "BPO Call Centers, Transport Logistics, Tech & Healthcare"),
        ("Brantford", "Ontario", 104688, "Industrial & Port", False, "E-Commerce Distribution, Advanced Plastics & Food Mfg"),
        ("Saint John", "New Brunswick", 69885, "Industrial & Port", False, "Oil Refining (Irving), Deep-Water Port & Energy Export"),
        ("Thunder Bay", "Ontario", 108843, "Industrial & Port", False, "Grain Export Shipping, Mining Support & Forestry Tech"),
        ("Peterborough", "Ontario", 83651, "Regional Center", False, "Aerospace Components, Clean Technology & Higher Education"),
        ("Lethbridge", "Alberta", 101482, "Regional Center", False, "Irrigated Agricultural Trade, Food Processing & Research"),
        ("Nanaimo", "British Columbia", 99863, "Industrial & Port", False, "Forestry Products, Marine Services & Regional Healthcare"),
        ("Kamloops", "British Columbia", 97902, "Regional Center", False, "Forestry, Copper Mining Logistics & Transportation Hub"),
        ("Belleville", "Ontario", 55071, "Industrial & Port", False, "Plastics Manufacturing, Food Processing & Distribution"),
        ("Chatham-Kent", "Ontario", 101647, "Regional Center", False, "Agribusiness, Heavy Equipment & Renewable Solar/Wind"),
        ("Fredericton", "New Brunswick", 63116, "Tech Hub", False, "Provincial Governance, Cybersecurity R&D & Forestry Tech"),
        ("Saint-Jean-sur-Richelieu", "Quebec", 98036, "Industrial & Port", False, "Aerospace Components, Defense Training & Textiles"),
        ("Red Deer", "Alberta", 100844, "Regional Center", False, "Oilfield Equipment Services, Petrochemicals & Livestock"),
        ("Cape Breton", "Nova Scotia", 93780, "Regional Center", False, "Green Energy Transition, Maritime Trades & Call Centers"),
        ("Chilliwack", "British Columbia", 93203, "Regional Center", False, "Agricultural Processing, Manufacturing & Construction"),
        ("Whitehorse", "Yukon", 28201, "Capital", True, "Territorial Administration, Mining Services & Eco-Tourism"),
        ("Yellowknife", "Northwest Territories", 20340, "Capital", True, "Territorial Governance, Diamond Mining Support & Aviation"),
        ("Iqaluit", "Nunavut", 7740, "Capital", True, "Nunavut Governance, Arctic Logistics & Indigenous Craft")
    ]
}

with open("./scripts/world_cities_dict.json", "w") as f:
    json.dump(FACTUAL_WORLD_CITIES, f, indent=2)

print(f"Base factual world cities stored for {len(FACTUAL_WORLD_CITIES)} key countries.")
