import json
import os
import random

# Load countries metadata
with open("./scripts/countries_info.json", "r") as f:
    countries_meta = json.load(f)

print(f"Loaded metadata for {len(countries_meta)} countries.")

# Real specific city data dictionary for top countries
REAL_CITIES_DATA = {
    "US": [
        ("New York City", "New York", 8804190, "Financial Hub", False, "Finance, FinTech, Media, Technology & Fashion", ["English", "Spanish", "Chinese"]),
        ("Los Angeles", "California", 3898747, "Tech Hub", False, "Entertainment, Silicon Beach Tech, Logistics & Aerospace", ["English", "Spanish", "Korean"]),
        ("Chicago", "Illinois", 2746388, "Financial Hub", False, "Trading, Manufacturing, Enterprise Software & Healthcare", ["English", "Spanish", "Polish"]),
        ("Houston", "Texas", 2304580, "Industrial & Port", False, "Energy, Medical Research (Texas Medical Center) & Aerospace", ["English", "Spanish", "Vietnamese"]),
        ("Phoenix", "Arizona", 1608139, "Major City", True, "Semiconductors, Healthcare & Financial Operations", ["English", "Spanish"]),
        ("Philadelphia", "Pennsylvania", 1603797, "Major City", False, "Biotech, Education, Healthcare & Legal Services", ["English", "Spanish"]),
        ("San Antonio", "Texas", 1434625, "Major City", False, "Cybersecurity, Defense, Healthcare & Tourism", ["English", "Spanish"]),
        ("San Diego", "California", 1386932, "Tech Hub", False, "Biotech, Life Sciences, Defense & Wireless Tech", ["English", "Spanish"]),
        ("Dallas", "Texas", 1304379, "Financial Hub", False, "Telecom (Telecom Corridor), Defense & Corporate HQs", ["English", "Spanish"]),
        ("San Jose", "California", 1013240, "Tech Hub", False, "Silicon Valley Capital, Hardware, AI & Software R&D", ["English", "Spanish", "Vietnamese", "Mandarin"]),
        ("Austin", "Texas", 974447, "Tech Hub", True, "Silicon Hills Tech, Startups, Gaming & Clean Energy", ["English", "Spanish"]),
        ("Jacksonville", "Florida", 949611, "Industrial & Port", False, "Logistics, Naval Defense, Healthcare & FinTech", ["English", "Spanish"]),
        ("Fort Worth", "Texas", 918915, "Major City", False, "Aerospace (Lockheed Martin), Defense, Mobility & Agriculture", ["English", "Spanish"]),
        ("Columbus", "Ohio", 905748, "Tech Hub", True, "Silicon Heartland (Intel Fab), InsurTech, E-Commerce Logistics", ["English", "Somali", "Spanish"]),
        ("Charlotte", "North Carolina", 874579, "Financial Hub", False, "Bank of America / Wells Fargo Finance, Energy & Tech", ["English", "Spanish"]),
        ("Indianapolis", "Indiana", 887642, "Regional Center", True, "Pharmaceuticals (Eli Lilly), Logistics, Sports & SaaS", ["English", "Spanish"]),
        ("San Francisco", "California", 873965, "Tech Hub", False, "GenAI Capital, Venture Capital, SaaS & Cloud Computing", ["English", "Chinese", "Spanish"]),
        ("Seattle", "Washington", 737015, "Tech Hub", False, "Cloud Infrastructure (AWS/Azure), E-Commerce & Aerospace", ["English", "Spanish", "Chinese"]),
        ("Denver", "Colorado", 715522, "Regional Center", True, "Telecom, Space Tech, Cleantech & Financial Operations", ["English", "Spanish"]),
        ("Washington", "District of Columbia", 689545, "Capital", True, "Federal Government, GovTech, Defense, Legal & Consulting", ["English", "Spanish", "French"]),
        ("Nashville", "Tennessee", 689447, "Major City", True, "Healthcare Management, Music Industry, EV Tech & Finance", ["English", "Spanish"]),
        ("Oklahoma City", "Oklahoma", 681054, "Regional Center", True, "Aviation Maintenance, Energy & Biotechnology", ["English", "Spanish"]),
        ("El Paso", "Texas", 678815, "Major City", False, "Cross-Border Logistics, Defense & Bilingual Customer Support", ["Spanish", "English"]),
        ("Boston", "Massachusetts", 675647, "Tech Hub", True, "Pharma/Biotech, Higher Education, Robotics & AI R&D", ["English", "Spanish", "Chinese", "Portuguese"]),
        ("Portland", "Oregon", 652503, "Tech Hub", False, "Silicon Forest Semiconductor (Intel), Sportswear & CleanTech", ["English", "Spanish", "Vietnamese"]),
        ("Las Vegas", "Nevada", 641903, "Major City", False, "Hospitality Tech, Gaming, Clean Energy & Battery Manufacturing", ["English", "Spanish", "Tagalog"]),
        ("Detroit", "Michigan", 639111, "Industrial & Port", False, "Automotive EV Innovation (Ford/GM), Robotics & Mobility Software", ["English", "Spanish", "Arabic"]),
        ("Memphis", "Tennessee", 633104, "Industrial & Port", False, "Global Air Cargo Logistics (FedEx Superhub) & Biomedical Devices", ["English", "Spanish"]),
        ("Louisville", "Kentucky", 633045, "Regional Center", False, "UPS Worldport Logistics, Healthcare Operations & Spirits", ["English", "Spanish"]),
        ("Baltimore", "Maryland", 585708, "Major City", False, "Johns Hopkins Medical Research, Cyber Defense & Maritime Shipping", ["English", "Spanish"]),
        ("Milwaukee", "Wisconsin", 577222, "Industrial & Port", False, "Precision Industrial Machinery, Healthcare Software & WaterTech", ["English", "Spanish", "Hmong"]),
        ("Albuquerque", "New Mexico", 564559, "Tech Hub", False, "Sandia National Labs Defense Tech, Solar Energy & Space Systems", ["English", "Spanish", "Navajo"]),
        ("Tucson", "Arizona", 542519, "Tech Hub", False, "Raytheon Defense Systems, Optics Valley & Astronomy Research", ["English", "Spanish"]),
        ("Fresno", "California", 542107, "Regional Center", False, "AgTech Innovation, Food Processing & Central Valley Distribution", ["English", "Spanish", "Hmong"]),
        ("Sacramento", "California", 524943, "Capital", True, "California State Government, Public Policy, CleanTech & Healthcare", ["English", "Spanish", "Chinese"]),
        ("Atlanta", "Georgia", 498715, "Financial Hub", True, "FinTech (Transaction Alley), Logistics, Media & Software", ["English", "Spanish"]),
        ("Omaha", "Nebraska", 486051, "Financial Hub", False, "Berkshire Hathaway Financial HQs, InsurTech & Railroad Logistics", ["English", "Spanish"]),
        ("Colorado Springs", "Colorado", 478961, "Major City", False, "US Space Command, Aerospace, Cyber Security & Defense Technology", ["English", "Spanish"]),
        ("Raleigh", "North Carolina", 467665, "Tech Hub", True, "Research Triangle Park (RTP) Software, Biotech & CleanTech", ["English", "Spanish"]),
        ("Miami", "Florida", 442241, "Financial Hub", False, "Latin America LATAM HQs, Crypto, International Banking & Trade", ["Spanish", "English", "Haitian Creole"]),
        ("Oakland", "California", 440646, "Industrial & Port", False, "Port of Oakland Container Logistics, GreenTech & Creative Tech", ["English", "Spanish", "Chinese"]),
        ("Minneapolis", "Minnesota", 429954, "Financial Hub", False, "Target/Best Buy Corporate HQs, Medical Device Tech & Banking", ["English", "Somali", "Spanish"]),
        ("Tulsa", "Oklahoma", 413066, "Major City", False, "Tulsa Remote Tech Incentive, Energy Tech & Aerospace Repair", ["English", "Spanish"]),
        ("Tampa", "Florida", 384959, "Financial Hub", False, "Financial Shared Services, Cyber Defense & Healthcare Innovation", ["English", "Spanish"]),
        ("Arlington", "Virginia", 238643, "Tech Hub", False, "Amazon HQ2, Pentagon Defense Contracting, GovTech & Cyber", ["English", "Spanish", "Amharic"]),
        ("Salt Lake City", "Utah", 199723, "Tech Hub", True, "Silicon Slopes SaaS, Life Sciences, FinTech & Outdoor Industry", ["English", "Spanish"])
    ]
}

# Extensive lists of real world cities for remaining top countries
REAL_WORLD_CITIES_EXTENDED = {
    "GB": [
        ("London", "Greater London", 8982000, "Capital", True, "Global Financial Services, FinTech, Media, Technology & AI R&D", ["English"]),
        ("Birmingham", "West Midlands", 1149000, "Major City", False, "Automotive Engineering, Jewelry Quarter, Tech & Financial Shared Services", ["English", "Panjabi", "Urdu"]),
        ("Glasgow", "Scotland", 635640, "Major City", False, "Shipbuilding & Marine Engineering, Life Sciences, Software & Finance", ["English", "Gaelic"]),
        ("Manchester", "North West", 553230, "Tech Hub", False, "MediaCityUK, E-Commerce Tech, Cyber Security & Higher Education", ["English", "Urdu", "Arabic"]),
        ("Liverpool", "North West", 498042, "Industrial & Port", False, "Deepwater Container Port, Life Sciences, Creative Digital & Automotive", ["English"]),
        ("Bristol", "South West", 472400, "Tech Hub", False, "Aerospace (Airbus/Rolls-Royce), Microelectronics, CleanTech & Media", ["English"]),
        ("Edinburgh", "Scotland", 488050, "Capital", True, "Scottish Financial Center, AI Research, Software Tech & Tourism", ["English", "Gaelic"]),
        ("Leeds", "Yorkshire and the Humber", 516298, "Financial Hub", False, "UK Second Financial & Legal Center, HealthTech & Digital Media", ["English", "Polish", "Urdu"]),
        ("Sheffield", "Yorkshire and the Humber", 584853, "Industrial & Port", False, "Advanced Manufacturing Research Center (AMRC), Metals & Health Sciences", ["English"]),
        ("Newcastle upon Tyne", "North East", 300194, "Tech Hub", False, "Offshore Renewable Energy, Gaming Tech, Cyber & Life Sciences", ["English"]),
        ("Belfast", "Northern Ireland", 343542, "Capital", True, "Cyber Security, Film & TV Production, FinTech & Aerospace", ["English", "Irish"]),
        ("Leicester", "East Midlands", 368600, "Major City", False, "Textiles Manufacturing, Space Park Leicester, E-Commerce & Health", ["English", "Gujarati", "Punjabi"]),
        ("Coventry", "West Midlands", 345300, "Industrial & Port", False, "UK Battery Industrialisation Centre, Automotive Engineering & Robotics", ["English"]),
        ("Nottingham", "East Midlands", 323700, "Tech Hub", False, "Pharma BioCity Incubator, Clean Energy, Software & Retail HQs", ["English"]),
        ("Southampton", "South East", 252520, "Industrial & Port", False, "Cruise & Container Seaport Logistics, Marine Autonomy & Oceanography", ["English"]),
        ("Portsmouth", "South East", 208100, "Industrial & Port", False, "Royal Navy Base, Naval Defense Engineering & Maritime Tech", ["English"]),
        ("Aberdeen", "Scotland", 198590, "Industrial & Port", False, "European Energy Capital, Offshore Wind, Hydrogen & Subsea Tech", ["English", "Gaelic"]),
        ("Dundee", "Scotland", 148210, "Tech Hub", False, "Video Games Industry, Life Sciences & Design", ["English"]),
        ("Swansea", "Wales", 246500, "Regional Center", False, "DVLA Tech Hub, Marine Energy, Materials Engineering & Healthcare", ["English", "Welsh"]),
        ("Cardiff", "Wales", 362400, "Capital", True, "Welsh Capital, Creative Industries, InsurTech & Public Sector", ["English", "Welsh"]),
        ("Plymouth", "South West", 262100, "Industrial & Port", False, "Naval Defense, Marine Autonomy & Composite Materials", ["English"]),
        ("Brighton & Hove", "South East", 277900, "Tech Hub", False, "Silicon Beach Creative Digital Tech, AI Startups & Green Energy", ["English"]),
        ("Oxford", "South East", 152450, "Tech Hub", False, "Oxford Science Park, Biotech, Quantum Computing & Automotive", ["English"]),
        ("Cambridge", "East of England", 145700, "Tech Hub", False, "Silicon Fen Tech Hub, Biotech, AI & Venture Capital", ["English"]),
        ("Norwich", "East of England", 143135, "Regional Center", False, "Norwich Research Park, Agri-Tech & Financial Services", ["English"]),
        ("York", "Yorkshire and the Humber", 211000, "Regional Center", False, "Railway Tech Engineering, Agritech & Heritage Tourism", ["English"]),
        ("Bath", "South West", 101102, "Regional Center", False, "Software Tech, Architecture, Higher Education & Heritage Tourism", ["English"]),
        ("Exeter", "South West", 130700, "Regional Center", False, "Climate Analytics, Environmental Science & Financial Services", ["English"]),
        ("Chester", "North West", 118200, "Regional Center", False, "Financial Shared Services, Aerospace & Retail", ["English"]),
        ("Milton Keynes", "South East", 229941, "Tech Hub", False, "Logistics Distribution, Robotics & Formula 1 Engineering", ["English"])
    ],
    "DE": [
        ("Berlin", "Berlin", 3755000, "Capital", True, "Global Tech Startup Capital, Creative Digital, AI & GovTech", ["German", "English"]),
        ("Hamburg", "Hamburg", 1890000, "Industrial & Port", False, "Port of Hamburg Container Shipping, Aviation & Renewable Energy", ["German", "English"]),
        ("Munich", "Bavaria", 1580000, "Tech Hub", False, "BMW HQs, Siemens, Automotive Software & Quantum Tech", ["German", "English"]),
        ("Cologne", "North Rhine-Westphalia", 1080000, "Major City", False, "Media & Games Industry, Chemical Industry & Trade Fairs", ["German"]),
        ("Frankfurt am Main", "Hessen", 764000, "Financial Hub", False, "European Central Bank, Financial Services & Data Centers", ["German", "English"]),
        ("Stuttgart", "Baden-Württemberg", 630000, "Industrial & Port", False, "Automotive Capital (Mercedes/Porsche) & Precision Machinery", ["German"]),
        ("Düsseldorf", "North Rhine-Westphalia", 620000, "Financial Hub", False, "Telecom, Fashion, Corporate Law & Foreign Trade", ["German", "Japanese"]),
        ("Leipzig", "Saxony", 615000, "Tech Hub", False, "DHL Air Hub, Automotive Fabs & BioCity", ["German"]),
        ("Dortmund", "North Rhine-Westphalia", 588000, "Tech Hub", False, "Micro-and Nanotechnology, Digital Logistics & E-Commerce", ["German"]),
        ("Essen", "North Rhine-Westphalia", 582000, "Industrial & Port", False, "Energy Capital (RWE/E.ON) & Industrial Engineering", ["German"]),
        ("Bremen", "Bremen", 569000, "Industrial & Port", False, "Aerospace & Space Technology & Seaport Logistics", ["German"]),
        ("Dresden", "Saxony", 556000, "Tech Hub", False, "Silicon Saxony Microelectronics & Nanotech", ["German"]),
        ("Hannover", "Lower Saxony", 537000, "Industrial & Port", False, "Industrial Tech, Tires & Insurance", ["German"]),
        ("Nuremberg", "Bavaria", 518000, "Tech Hub", False, "Power Electronics, Automation & IT Services", ["German"]),
        ("Duisburg", "North Rhine-Westphalia", 495000, "Industrial & Port", False, "Inland Port, Steel Manufacturing & Logistics", ["German"]),
        ("Bochum", "North Rhine-Westphalia", 364000, "Tech Hub", False, "Cyber Security Center & IT Safety", ["German"]),
        ("Wuppertal", "North Rhine-Westphalia", 355000, "Regional Center", False, "Textile Machinery, Chemical Pharma & Circular Economy", ["German"]),
        ("Bielefeld", "North Rhine-Westphalia", 334000, "Regional Center", False, "IT Consulting, Food Tech & Machinery", ["German"]),
        ("Bonn", "North Rhine-Westphalia", 331000, "Regional Center", False, "UN Organizations & Deutsche Telekom HQs", ["German", "English"]),
        ("Münster", "North Rhine-Westphalia", 317000, "Regional Center", False, "Nanobiotechnology & Battery Research Center", ["German"]),
        ("Karlsruhe", "Baden-Württemberg", 308000, "Tech Hub", False, "Cyber Security, Computer Science & AI", ["German"]),
        ("Mannheim", "Baden-Württemberg", 311000, "Industrial & Port", False, "Chemicals, Automotive Engines & Medical Tech", ["German"]),
        ("Augsburg", "Bavaria", 296000, "Industrial & Port", False, "Robotics, Mechatronics & Aerospace Composites", ["German"]),
        ("Wiesbaden", "Hessen", 278000, "Capital", True, "Federal Criminal Police, State Government & Healthcare", ["German"]),
        ("Aachen", "North Rhine-Westphalia", 249000, "Tech Hub", False, "Engineering Center, Electric Mobility & Laser Tech", ["German"])
    ],
    "FR": [
        ("Paris", "Île-de-France", 2148000, "Capital", True, "Global Fashion, Luxury Goods, FinTech, AI & Government", ["French", "English"]),
        ("Marseille", "Provence-Alpes-Côte d'Azur", 870000, "Industrial & Port", False, "Mediterranean Container Port, Subsea Cables & Logistics", ["French", "Arabic"]),
        ("Lyon", "Auvergne-Rhône-Alpes", 522000, "Tech Hub", False, "Biotech, Vaccines, CleanTech & Software", ["French"]),
        ("Toulouse", "Occitanie", 498000, "Tech Hub", False, "European Aerospace Capital (Airbus), Space Systems & AI", ["French", "English"]),
        ("Nice", "Provence-Alpes-Côte d'Azur", 342000, "Tech Hub", False, "Sophia Antipolis Tech Park, Tourism & Marine Tech", ["French", "English"]),
        ("Nantes", "Pays de la Loire", 320000, "Tech Hub", False, "Digital Tech Startups, Composite Materials & Offshore Wind", ["French"]),
        ("Montpellier", "Occitanie", 299000, "Tech Hub", False, "Healthtech, Agritech, Video Games & Higher Education", ["French"]),
        ("Strasbourg", "Grand Est", 287000, "Capital", True, "European Parliament, Medical Devices & Law", ["French", "German"]),
        ("Bordeaux", "Nouvelle-Aquitaine", 260000, "Tech Hub", False, "Wine Trade, Aerospace, Optics & Software", ["French"]),
        ("Lille", "Hauts-de-France", 236000, "Financial Hub", False, "E-Commerce Retailing, FinTech & Materials Science", ["French"]),
        ("Rennes", "Brittany", 222000, "Tech Hub", False, "Cyber Security Center, Telecom Software & Agri-Food", ["French"]),
        ("Reims", "Grand Est", 182000, "Regional Center", False, "Champagne Trade, Agribusiness & Biorefineries", ["French"]),
        ("Toulon", "Provence-Alpes-Côte d'Azur", 179000, "Industrial & Port", False, "French Navy Fleet Base, Naval Defense & Oceanography", ["French"]),
        ("Saint-Étienne", "Auvergne-Rhône-Alpes", 173000, "Industrial & Port", False, "Design Capital, Advanced Manufacturing & Optics", ["French"]),
        ("Le Havre", "Normandy", 166000, "Industrial & Port", False, "Container Gateway Port, Petrochemicals & Wind Energy", ["French"]),
        ("Grenoble", "Auvergne-Rhône-Alpes", 158000, "Tech Hub", False, "Microelectronics, Nanotech & Research", ["French", "English"]),
        ("Dijon", "Bourgogne-Franche-Comté", 159000, "Regional Center", False, "Agritech, Food Valley & Pharmaceuticals", ["French"]),
        ("Angers", "Pays de la Loire", 155000, "Tech Hub", False, "Electronics Manufacturing Services, Plant Biotech & IoT", ["French"]),
        ("Nîmes", "Occitanie", 148000, "Regional Center", False, "Textiles Heritage, Agricultural Logistics & Tourism", ["French"]),
        ("Villeurbanne", "Auvergne-Rhône-Alpes", 152000, "Major City", False, "Higher Education Engineering Campus & Software", ["French"])
    ],
    "JP": [
        ("Tokyo", "Tokyo Metropolis", 13960000, "Capital", True, "Global Megacity, Robotics, AI, Finance & Gaming", ["Japanese"]),
        ("Yokohama", "Kanagawa", 3770000, "Industrial & Port", False, "Deepwater Seaport, Automotive, Biotech & Electronics", ["Japanese"]),
        ("Osaka", "Osaka", 2750000, "Financial Hub", False, "Commercial Capital, Pharmaceuticals & Electronics", ["Japanese"]),
        ("Nagoya", "Aichi", 2330000, "Industrial & Port", False, "Toyota Automotive Hub, Aerospace & Machine Tools", ["Japanese"]),
        ("Sapporo", "Hokkaido", 1970000, "Regional Center", False, "IT Software, Agribusiness & Snow Tourism", ["Japanese"]),
        ("Kobe", "Hyogo", 1520000, "Industrial & Port", False, "Supercomputing, Medical Industry City & Heavy Machinery", ["Japanese"]),
        ("Kyoto", "Kyoto", 1460000, "Tech Hub", False, "Nintendo HQs, Precision Electronics & Culture", ["Japanese"]),
        ("Fukuoka", "Fukuoka", 1610000, "Tech Hub", False, "National Startup Zone, E-Commerce & Software", ["Japanese"]),
        ("Kawasaki", "Kanagawa", 1540000, "Industrial & Port", False, "R&D Science Parks, Chemicals & High-Tech", ["Japanese"]),
        ("Saitama", "Saitama", 1320000, "Major City", False, "Precision Machinery & Greater Tokyo Logistics", ["Japanese"]),
        ("Hiroshima", "Hiroshima", 1190000, "Industrial & Port", False, "Mazda Automotive Manufacturing, Shipbuilding & Steel", ["Japanese"]),
        ("Sendai", "Miyagi", 1090000, "Regional Center", False, "Tohoku Tech Hub & Semiconductor Materials", ["Japanese"]),
        ("Chiba", "Chiba", 980000, "Industrial & Port", False, "Industrial Belt, Tech Expo & Logistics", ["Japanese"]),
        ("Kitakyushu", "Fukuoka", 935000, "Industrial & Port", False, "Robot Capital, Eco-Tech Recycling & Steel", ["Japanese"]),
        ("Sakai", "Osaka", 825000, "Industrial & Port", False, "Display Fabs, Bicycle Components & Machine Tools", ["Japanese"]),
        ("Niigata", "Niigata", 790000, "Industrial & Port", False, "Sea Port Logistics, Rice Agribusiness & Chemicals", ["Japanese"]),
        ("Hamamatsu", "Shizuoka", 790000, "Industrial & Port", False, "Musical Instrument Capital, Auto & Photonics", ["Japanese"]),
        ("Kumamoto", "Kumamoto", 738000, "Tech Hub", False, "Silicon Island Semiconductor Mega-Fab & AgTech", ["Japanese"]),
        ("Sagamihara", "Kanagawa", 725000, "Tech Hub", False, "JAXA Space Campus, Robotics & Automotive", ["Japanese"]),
        ("Okayama", "Okayama", 720000, "Industrial & Port", False, "Textile Manufacturing, Synthetic Fibers & Medical", ["Japanese"])
    ]
}

print("Loaded base extended real cities.")
