import json
import os

# We build a massive dataset of genuine real cities for all world nations

countries_db = {}

def add(code, cities):
    countries_db[code] = cities

# United States (100+ real cities)
add("US", [
    ("New York City", "New York", 8804190, "Financial Hub", True, "Finance, FinTech, Media, Technology & Fashion", ["English", "Spanish", "Chinese"]),
    ("Los Angeles", "California", 3898747, "Tech Hub", False, "Entertainment, Silicon Beach Tech, Logistics & Aerospace", ["English", "Spanish", "Korean"]),
    ("Chicago", "Illinois", 2746388, "Financial Hub", False, "Trading, Manufacturing, Enterprise Software & Healthcare", ["English", "Spanish", "Polish"]),
    ("Houston", "Texas", 2304580, "Industrial & Port", False, "Energy, Medical Research (Texas Medical Center) & Aerospace", ["English", "Spanish", "Vietnamese"]),
    ("Phoenix", "Arizona", 1608139, "Major City", True, "Semiconductors, Healthcare & Financial Operations", ["English", "Spanish"]),
    ("Philadelphia", "Pennsylvania", 1603797, "Major City", False, "Biotech, Education, Healthcare & Legal Services", ["English", "Spanish"]),
    ("San Antonio", "Texas", 1434625, "Major City", False, "Cybersecurity, Defense, Healthcare & Tourism", ["English", "Spanish"]),
    ("San Diego", "California", 1386932, "Tech Hub", False, "Biotech, Life Sciences, Defense & Wireless Tech", ["English", "Spanish"]),
    ("Dallas", "Texas", 1304379, "Financial Hub", False, "Telecom (Telecom Corridor), Defense & Corporate HQs", ["English", "Spanish"]),
    ("San Jose", "California", 1013240, "Tech Hub", False, "Silicon Valley Capital, Hardware, AI & Software R&D", ["English", "Spanish", "Vietnamese"]),
    ("Austin", "Texas", 974447, "Tech Hub", True, "Silicon Hills Tech, Startups, Gaming & Clean Energy", ["English", "Spanish"]),
    ("Jacksonville", "Florida", 949611, "Industrial & Port", False, "Logistics, Naval Defense, Healthcare & FinTech", ["English", "Spanish"]),
    ("Fort Worth", "Texas", 918915, "Major City", False, "Aerospace (Lockheed Martin), Defense, Mobility & Agriculture", ["English", "Spanish"]),
    ("Columbus", "Ohio", 905748, "Tech Hub", True, "Silicon Heartland (Intel Fab), InsurTech, E-Commerce Logistics", ["English", "Somali"]),
    ("Charlotte", "North Carolina", 874579, "Financial Hub", False, "Bank of America / Wells Fargo Finance, Energy & Tech", ["English", "Spanish"]),
    ("Indianapolis", "Indiana", 887642, "Regional Center", True, "Pharmaceuticals (Eli Lilly), Logistics, Sports & SaaS", ["English", "Spanish"]),
    ("San Francisco", "California", 873965, "Tech Hub", False, "GenAI Capital, Venture Capital, SaaS & Cloud Computing", ["English", "Chinese"]),
    ("Seattle", "Washington", 737015, "Tech Hub", False, "Cloud Infrastructure (AWS/Azure), E-Commerce & Aerospace", ["English", "Chinese"]),
    ("Denver", "Colorado", 715522, "Regional Center", True, "Telecom, Space Tech, Cleantech & Financial Operations", ["English", "Spanish"]),
    ("Washington", "District of Columbia", 689545, "Capital", True, "Federal Government, GovTech, Defense, Legal & Consulting", ["English", "French"]),
    ("Nashville", "Tennessee", 689447, "Major City", True, "Healthcare Management, Music Industry, EV Tech & Finance", ["English", "Spanish"]),
    ("Oklahoma City", "Oklahoma", 681054, "Regional Center", True, "Aviation Maintenance, Energy & Biotechnology", ["English", "Spanish"]),
    ("El Paso", "Texas", 678815, "Major City", False, "Cross-Border Logistics, Defense & Bilingual Customer Support", ["Spanish", "English"]),
    ("Boston", "Massachusetts", 675647, "Tech Hub", True, "Pharma/Biotech, Higher Education, Robotics & AI R&D", ["English", "Spanish"]),
    ("Portland", "Oregon", 652503, "Tech Hub", False, "Silicon Forest Semiconductor (Intel), Sportswear & CleanTech", ["English", "Spanish"]),
    ("Las Vegas", "Nevada", 641903, "Major City", False, "Hospitality Tech, Gaming, Clean Energy & Battery Manufacturing", ["English", "Spanish"]),
    ("Detroit", "Michigan", 639111, "Industrial & Port", False, "Automotive EV Innovation (Ford/GM), Robotics & Mobility Software", ["English", "Arabic"]),
    ("Memphis", "Tennessee", 633104, "Industrial & Port", False, "Global Air Cargo Logistics (FedEx Superhub) & Biomedical Devices", ["English", "Spanish"]),
    ("Louisville", "Kentucky", 633045, "Regional Center", False, "UPS Worldport Logistics, Healthcare Operations & Spirits", ["English", "Spanish"]),
    ("Baltimore", "Maryland", 585708, "Major City", False, "Johns Hopkins Medical Research, Cyber Defense & Maritime Shipping", ["English", "Spanish"]),
    ("Milwaukee", "Wisconsin", 577222, "Industrial & Port", False, "Precision Industrial Machinery, Healthcare Software & WaterTech", ["English", "Spanish"]),
    ("Albuquerque", "New Mexico", 564559, "Tech Hub", False, "Sandia National Labs Defense Tech, Solar Energy & Space Systems", ["English", "Spanish"]),
    ("Tucson", "Arizona", 542519, "Tech Hub", False, "Raytheon Defense Systems, Optics Valley & Astronomy Research", ["English", "Spanish"]),
    ("Fresno", "California", 542107, "Regional Center", False, "AgTech Innovation, Food Processing & Central Valley Logistics", ["English", "Spanish"]),
    ("Sacramento", "California", 524943, "Capital", True, "California State Government, Public Policy, CleanTech & Healthcare", ["English", "Spanish"]),
    ("Atlanta", "Georgia", 498715, "Financial Hub", True, "FinTech (Transaction Alley), Logistics, Media & Software", ["English", "Spanish"]),
    ("Omaha", "Nebraska", 486051, "Financial Hub", False, "Berkshire Hathaway Financial HQs, InsurTech & Railroad Logistics", ["English", "Spanish"]),
    ("Colorado Springs", "Colorado", 478961, "Major City", False, "US Space Command, Aerospace, Cyber Security & Defense Technology", ["English", "Spanish"]),
    ("Raleigh", "North Carolina", 467665, "Tech Hub", True, "Research Triangle Park (RTP) Software, Biotech & CleanTech", ["English", "Spanish"]),
    ("Miami", "Florida", 442241, "Financial Hub", False, "Latin America LATAM HQs, Crypto, International Banking & Trade", ["Spanish", "English"]),
    ("Oakland", "California", 440646, "Industrial & Port", False, "Port of Oakland Container Logistics, GreenTech & Creative Tech", ["English", "Spanish"]),
    ("Minneapolis", "Minnesota", 429954, "Financial Hub", False, "Target/Best Buy Corporate HQs, Medical Device Tech & Banking", ["English", "Somali"]),
    ("Tulsa", "Oklahoma", 413066, "Major City", False, "Tulsa Remote Tech Incentive, Energy Tech & Aerospace Repair", ["English", "Spanish"]),
    ("Tampa", "Florida", 384959, "Financial Hub", False, "Financial Shared Services, Cyber Defense & Healthcare Innovation", ["English", "Spanish"]),
    ("Arlington", "Virginia", 238643, "Tech Hub", False, "Amazon HQ2, Pentagon Defense Contracting, GovTech & Cyber", ["English", "Spanish"]),
    ("Salt Lake City", "Utah", 199723, "Tech Hub", True, "Silicon Slopes SaaS, Life Sciences, FinTech & Outdoor Industry", ["English", "Spanish"]),
    ("Kansas City", "Missouri", 508090, "Regional Center", False, "AgTech, Logistics, Animal Health Corridor & Architecture", ["English"]),
    ("Mesa", "Arizona", 504258, "Tech Hub", False, "Aerospace Components, Semiconductor Fabrication & Education", ["English", "Spanish"]),
    ("Virginia Beach", "Virginia", 459470, "Industrial & Port", False, "Subsea Fiber Cable Landing Station, Defense & Maritime", ["English"]),
    ("Bakersfield", "California", 403455, "Regional Center", False, "Energy Production, Agriculture & Central Valley Logistics", ["English", "Spanish"]),
    ("Aurora", "Colorado", 386261, "Major City", False, "Anschutz Medical Campus, Aerospace & Defense Contracting", ["English", "Spanish"]),
    ("Anaheim", "California", 346824, "Major City", False, "Hospitality Tech, Entertainment & Software", ["English", "Spanish"]),
    ("Corpus Christi", "Texas", 317863, "Industrial & Port", False, "Petrochemical Refineries, Port Logistics & Naval Air", ["English", "Spanish"]),
    ("Riverside", "California", 314998, "Regional Center", False, "Logistics Warehousing, Clean Air Research & Education", ["English", "Spanish"]),
    ("Lexington", "Kentucky", 322570, "Regional Center", False, "Equine Biotech, Animal Health & Higher Education", ["English"]),
    ("Stockton", "California", 320804, "Industrial & Port", False, "Inland Port Container Logistics & Agribusiness Processing", ["English", "Spanish"]),
    ("Anchorage", "Alaska", 291247, "Regional Center", False, "Global Air Cargo Transit (Ted Stevens Hub) & Resource Energy", ["English"]),
    ("Cincinnati", "Ohio", 309317, "Financial Hub", False, "Procter & Gamble Corporate, FinTech & Aviation Engines", ["English"]),
    ("St. Louis", "Missouri", 301574, "Tech Hub", False, "Cortex Innovation District, Plant Science & Financial Services", ["English"]),
    ("Greensboro", "North Carolina", 299035, "Major City", False, "Aviation Manufacturing (HondaJet), Supply Chain & Textiles", ["English"]),
    ("Plano", "Texas", 285494, "Tech Hub", False, "Legacy West Corporate HQs (Toyota/Frito-Lay) & Telecom", ["English", "Spanish"]),
    ("Irvine", "California", 307670, "Tech Hub", False, "Medical Devices, Video Game Software (Blizzard) & Semiconductor", ["English", "Mandarin"]),
    ("Newark", "New Jersey", 311549, "Industrial & Port", False, "Port Newark Shipping, Logistics, InsurTech & Legal", ["English", "Spanish"]),
    ("Durham", "North Carolina", 283506, "Tech Hub", False, "Research Triangle Park Biotech, Clinical Trials & Software", ["English"]),
    ("Chula Vista", "California", 275639, "Major City", False, "Cross-Border Technology Trade, Clean Energy & Healthcare", ["English", "Spanish"]),
    ("Orlando", "Florida", 307573, "Tech Hub", False, "Simulation & Training Software, Optics/Photonics & Gaming", ["English", "Spanish"]),
    ("Toledo", "Ohio", 270871, "Industrial & Port", False, "Glass Manufacturing, Automotive Assembly (Jeep) & Solar", ["English"]),
    ("Fort Wayne", "Indiana", 263886, "Regional Center", False, "Defense Electronics, Medical Devices & Automotive Parts", ["English"]),
    ("Madison", "Wisconsin", 269840, "Tech Hub", True, "Epic Systems Health Software, Biotech & State Government", ["English"]),
    ("Laredo", "Texas", 255205, "Industrial & Port", False, "Number 1 US Cross-Border Trucking Port & Customs Brokerage", ["Spanish", "English"]),
    ("Lubbock", "Texas", 257141, "Regional Center", False, "Cotton Trade, Agricultural Research & Regional Healthcare", ["English", "Spanish"]),
    ("Chandler", "Arizona", 275987, "Tech Hub", False, "Intel Semiconductor Mega-Fab, Autonomous Tech & Wireless", ["English"]),
    ("Buffalo", "New York", 278349, "Regional Center", False, "Medical Research (Roswell Park), Advanced Manufacturing & Clean Power", ["English"]),
    ("Reno", "Nevada", 264165, "Tech Hub", False, "Tahoe Reno Industrial Center (Tesla Gigafactory) & Logistics", ["English", "Spanish"]),
    ("Glendale", "Arizona", 248325, "Major City", False, "Sports Entertainment, Healthcare & Luke AFB Defense", ["English", "Spanish"]),
    ("Scottsdale", "Arizona", 241361, "Financial Hub", False, "Software SaaS, Healthcare Operations & Financial Wealth", ["English"]),
    ("St. Petersburg", "Florida", 258308, "Tech Hub", False, "Financial Wealth Management (Raymond James), Marine Tech & SaaS", ["English"]),
    ("Norfolk", "Virginia", 238005, "Industrial & Port", False, "World Largest Naval Base, Container Shipping & Maritime Repair", ["English"]),
    ("Gilbert", "Arizona", 267918, "Major City", False, "Biotech Sciences, Aerospace Systems & Clean Energy", ["English"]),
    ("Winston-Salem", "North Carolina", 249545, "Tech Hub", False, "Wake Forest Biotech Innovation Quarter & Financial Operations", ["English"]),
    ("Boise", "Idaho", 235684, "Tech Hub", True, "Micron Semiconductor HQs, Agribusiness & Software Tech", ["English"]),
    ("Spokane", "Washington", 228989, "Regional Center", False, "Healthcare Education, Clean Energy & Aerospace Component Machining", ["English"]),
    ("Des Moines", "Iowa", 214133, "Financial Hub", True, "Top 3 Global Insurance Center, FinTech & Agribusiness HQs", ["English"]),
    ("Tacoma", "Washington", 219346, "Industrial & Port", False, "Deepwater Container Shipping Port, Forest Products & Health", ["English"]),
    ("Richmond", "Virginia", 226610, "Financial Hub", True, "Federal Reserve District Bank, InsurTech, Tobacco Tech & Law", ["English"]),
    ("Huntsville", "Alabama", 215006, "Tech Hub", False, "Rocket City NASA Marshall Space Center, Defense & Cyber", ["English"]),
    ("Rochester", "New York", 211328, "Tech Hub", False, "Optics, Photonics & Imaging Capital (Kodak/Xerox Legacy)", ["English"]),
    ("Grand Rapids", "Michigan", 198917, "Regional Center", False, "Medical Mile BioResearch, Office Furniture (Steelcase) & Auto", ["English"]),
    ("Fayetteville", "Arkansas", 93949, "Regional Center", False, "Walmart / Tyson / J.B. Hunt Corporate Supply Chain Corridor", ["English"]),
    ("Peoria", "Illinois", 113150, "Industrial & Port", False, "Caterpillar Heavy Machinery Engineering & Healthcare", ["English"]),
    ("Providence", "Rhode Island", 190934, "Capital", True, "Design, Higher Education (Brown/RISD), Offshore Wind & Health", ["English"]),
    ("Worcester", "Massachusetts", 206518, "Tech Hub", False, "Biomanufacturing, Life Sciences Park & Higher Education", ["English"]),
    ("Akron", "Ohio", 190203, "Industrial & Port", False, "Polymer Innovation Center, Tire Tech R&D & Healthcare", ["English"]),
    ("Little Rock", "Arkansas", 202591, "Capital", True, "FinTech Software, Healthcare Systems & Public Policy", ["English"]),
    ("Augusta", "Georgia", 202081, "Tech Hub", False, "US Army Cyber Center of Excellence & Medical Health", ["English"]),
    ("Mobile", "Alabama", 187041, "Industrial & Port", False, "Airbus Aircraft Final Assembly, Maritime Shipbuilding & Steel", ["English"]),
    ("Charleston", "South Carolina", 150227, "Industrial & Port", False, "Boeing 787 Aircraft Assembly, Automotive (Volvo/BMW) & Port", ["English"]),
    ("Savannah", "Georgia", 147780, "Industrial & Port", False, "Fastest Growing East Coast Container Port & Gulfstream Aerospace", ["English"]),
    ("Shreveport", "Louisiana", 187593, "Regional Center", False, "Barksdale Air Force Cyber Defense & Healthcare", ["English"]),
    ("Davenport", "Iowa", 101724, "Industrial & Port", False, "John Deere Heavy Equipment Manufacturing & Mississippi Shipping", ["English"]),
    ("Cedar Rapids", "Iowa", 137710, "Tech Hub", False, "Collins Aerospace Avionics, Defense Communications & Grain Processing", ["English"]),
    ("Springfield", "Missouri", 169176, "Regional Center", False, "Stainless Steel Tank Manufacturing & Logistics", ["English"]),
    ("Fargo", "North Dakota", 125990, "Tech Hub", False, "Microsoft Business Applications Campus & AgTech Tech Park", ["English"]),
    ("Sioux Falls", "South Dakota", 192517, "Financial Hub", False, "National Credit Card Banking HQs, Health Tech & No State Tax Business", ["English"]),
    ("Lincoln", "Nebraska", 291082, "Capital", True, "Agritech Innovation, State Public Policy & Higher Education", ["English"]),
    ("Green Bay", "Wisconsin", 107395, "Industrial & Port", False, "Papermaking Machinery, Logistics & Food Processing", ["English"]),
    ("Erie", "Pennsylvania", 94831, "Industrial & Port", False, "Locomotive Manufacturing, Plastics & Lake Maritime Cargo", ["English"]),
    ("Scranton", "Pennsylvania", 76328, "Regional Center", False, "E-Commerce Logistics Distribution & Healthcare Services", ["English"]),
    ("Albany", "New York", 99224, "Capital", True, "Tech Valley Semiconductor Nanotech Complex (SUNY Poly) & State Gov", ["English"]),
    ("Allentown", "Pennsylvania", 125845, "Industrial & Port", False, "Industrial Gas HQs (Air Products), Trucking Logistics & Electronics", ["English"]),
    ("Bridgeport", "Connecticut", 148654, "Industrial & Port", False, "Precision Machining, Maritime Marine & Subcontracting", ["English"]),
    ("Stamford", "Connecticut", 135470, "Financial Hub", False, "Financial Hedge Funds, Media Networks & Corporate HQs", ["English"]),
    ("New Haven", "Connecticut", 134023, "Tech Hub", False, "Yale University Biotech Startups, Pharma & Legal", ["English"]),
    ("Hartford", "Connecticut", 121054, "Financial Hub", True, "Insurance Capital of the World, Defense Aerospace (Pratt & Whitney)", ["English"]),
    ("Burlington", "Vermont", 44703, "Tech Hub", False, "GLOBALFOUNDRIES Semiconductor Fab & Clean Tech", ["English"]),
    ("Portland", "Maine", 68408, "Regional Center", False, "Veterinary Diagnostics (IDEXX), Commercial Fishing & FinTech", ["English"]),
    ("Manchester", "New Hampshire", 115644, "Tech Hub", False, "Millyard Tech Incubator, ARMI Biofabrication & Financial Services", ["English"])
])

print("US data loaded...")
