import os
import json

cities_data = {}

# US
cities_data["US"] = [
    {"cityName": "New York City", "stateOrRegion": "New York", "population": 8804190, "cityType": "Financial Hub", "isCapital": False, "focus": "Finance, FinTech, Media, Technology & Fashion"},
    {"cityName": "Los Angeles", "stateOrRegion": "California", "population": 3898747, "cityType": "Tech Hub", "isCapital": False, "focus": "Entertainment, Silicon Beach Tech, Logistics & Aerospace"},
    {"cityName": "Chicago", "stateOrRegion": "Illinois", "population": 2746388, "cityType": "Financial Hub", "isCapital": False, "focus": "Trading, Manufacturing, Enterprise Software & Healthcare"},
    {"cityName": "Houston", "stateOrRegion": "Texas", "population": 2304580, "cityType": "Industrial & Port", "isCapital": False, "focus": "Energy, Medical Research (Texas Medical Center) & Aerospace"},
    {"cityName": "Phoenix", "stateOrRegion": "Arizona", "population": 1608139, "cityType": "Major City", "isCapital": True, "focus": "Semiconductors, Healthcare & Financial Operations"},
    {"cityName": "Philadelphia", "stateOrRegion": "Pennsylvania", "population": 1603797, "cityType": "Major City", "isCapital": False, "focus": "Biotech, Education, Healthcare & Legal Services"},
    {"cityName": "San Antonio", "stateOrRegion": "Texas", "population": 1434625, "cityType": "Major City", "isCapital": False, "focus": "Cybersecurity, Defense, Healthcare & Tourism"},
    {"cityName": "San Diego", "stateOrRegion": "California", "population": 1386932, "cityType": "Tech Hub", "isCapital": False, "focus": "Biotech, Life Sciences, Defense & Wireless Tech"},
    {"cityName": "Dallas", "stateOrRegion": "Texas", "population": 1304379, "cityType": "Financial Hub", "isCapital": False, "focus": "Telecom (Telecom Corridor), Defense & Corporate HQs"},
    {"cityName": "San Jose", "stateOrRegion": "California", "population": 1013240, "cityType": "Tech Hub", "isCapital": False, "focus": "Silicon Valley Capital, Hardware, AI & Software R&D"},
    {"cityName": "Austin", "stateOrRegion": "Texas", "population": 974447, "cityType": "Tech Hub", "isCapital": True, "focus": "Silicon Hills Tech, Startups, Gaming & Clean Energy"},
    {"cityName": "Jacksonville", "stateOrRegion": "Florida", "population": 949611, "cityType": "Industrial & Port", "isCapital": False, "focus": "Logistics, Naval Defense, Healthcare & FinTech"},
    {"cityName": "Fort Worth", "stateOrRegion": "Texas", "population": 918915, "cityType": "Major City", "isCapital": False, "focus": "Aerospace (Lockheed Martin), Defense, Mobility & Agriculture"},
    {"cityName": "Columbus", "stateOrRegion": "Ohio", "population": 905748, "cityType": "Tech Hub", "isCapital": True, "focus": "Silicon Heartland (Intel Fab), InsurTech, E-Commerce Logistics"},
    {"cityName": "Charlotte", "stateOrRegion": "North Carolina", "population": 874579, "cityType": "Financial Hub", "isCapital": False, "focus": "Bank of America / Wells Fargo Finance, Energy & Tech"},
    {"cityName": "Indianapolis", "stateOrRegion": "Indiana", "population": 887642, "cityType": "Regional Center", "isCapital": True, "focus": "Pharmaceuticals (Eli Lilly), Logistics, Sports & SaaS"},
    {"cityName": "San Francisco", "stateOrRegion": "California", "population": 873965, "cityType": "Tech Hub", "isCapital": False, "focus": "GenAI Capital, Venture Capital, SaaS & Cloud Computing"},
    {"cityName": "Seattle", "stateOrRegion": "Washington", "population": 737015, "cityType": "Tech Hub", "isCapital": False, "focus": "Cloud Infrastructure (AWS/Azure), E-Commerce & Aerospace"},
    {"cityName": "Denver", "stateOrRegion": "Colorado", "population": 715522, "cityType": "Regional Center", "isCapital": True, "focus": "Telecom, Space Tech, Cleantech & Financial Operations"},
    {"cityName": "Washington", "stateOrRegion": "District of Columbia", "population": 689545, "cityType": "Capital", "isCapital": True, "focus": "Federal Government, GovTech, Defense, Legal & Consulting"},
    {"cityName": "Nashville", "stateOrRegion": "Tennessee", "population": 689447, "cityType": "Major City", "isCapital": True, "focus": "Healthcare Management, Music Industry, EV Tech & Finance"},
    {"cityName": "Oklahoma City", "stateOrRegion": "Oklahoma", "population": 681054, "cityType": "Regional Center", "isCapital": True, "focus": "Aviation Maintenance, Energy & Biotechnology"},
    {"cityName": "El Paso", "stateOrRegion": "Texas", "population": 678815, "cityType": "Major City", "isCapital": False, "focus": "Cross-Border Logistics, Defense & Bilingual Customer Support"},
    {"cityName": "Boston", "stateOrRegion": "Massachusetts", "population": 675647, "cityType": "Tech Hub", "isCapital": True, "focus": "Pharma/Biotech, Higher Education, Robotics & AI R&D"},
    {"cityName": "Portland", "stateOrRegion": "Oregon", "population": 652503, "cityType": "Tech Hub", "isCapital": False, "focus": "Silicon Forest Semiconductor (Intel), Sportswear & CleanTech"},
    {"cityName": "Las Vegas", "stateOrRegion": "Nevada", "population": 641903, "cityType": "Major City", "isCapital": False, "focus": "Hospitality Tech, Gaming, Clean Energy & Battery Manufacturing"},
    {"cityName": "Detroit", "stateOrRegion": "Michigan", "population": 639111, "cityType": "Industrial & Port", "isCapital": False, "focus": "Automotive EV Innovation (Ford/GM), Robotics & Mobility Software"},
    {"cityName": "Memphis", "stateOrRegion": "Tennessee", "population": 633104, "cityType": "Industrial & Port", "isCapital": False, "focus": "Global Air Cargo Logistics (FedEx Superhub) & Biomedical Devices"},
    {"cityName": "Louisville", "stateOrRegion": "Kentucky", "population": 633045, "cityType": "Regional Center", "isCapital": False, "focus": "UPS Worldport Logistics, Healthcare Operations & Spirits"},
    {"cityName": "Baltimore", "stateOrRegion": "Maryland", "population": 585708, "cityType": "Major City", "isCapital": False, "focus": "Johns Hopkins Medical Research, Cyber Defense & Maritime Shipping"},
    {"cityName": "Milwaukee", "stateOrRegion": "Wisconsin", "population": 577222, "cityType": "Industrial & Port", "isCapital": False, "focus": "Precision Industrial Machinery, Healthcare Software & WaterTech"},
    {"cityName": "Albuquerque", "stateOrRegion": "New Mexico", "population": 564559, "cityType": "Tech Hub", "isCapital": False, "focus": "Sandia National Labs Defense Tech, Solar Energy & Space Systems"},
    {"cityName": "Tucson", "stateOrRegion": "Arizona", "population": 542519, "cityType": "Tech Hub", "isCapital": False, "focus": "Raytheon Defense Systems, Optics Valley & Astronomy Research"},
    {"cityName": "Fresno", "stateOrRegion": "California", "population": 542107, "cityType": "Regional Center", "isCapital": False, "focus": "AgTech Innovation, Food Processing & Central Valley Logistics"},
    {"cityName": "Sacramento", "stateOrRegion": "California", "population": 524943, "cityType": "Capital", "isCapital": True, "focus": "California State Government, Public Policy, CleanTech & Healthcare"},
    {"cityName": "Atlanta", "stateOrRegion": "Georgia", "population": 498715, "cityType": "Financial Hub", "isCapital": True, "focus": "FinTech (Transaction Alley), Logistics, Media & Software"},
    {"cityName": "Omaha", "stateOrRegion": "Nebraska", "population": 486051, "cityType": "Financial Hub", "isCapital": False, "focus": "Berkshire Hathaway Financial HQs, InsurTech & Railroad Logistics"},
    {"cityName": "Colorado Springs", "stateOrRegion": "Colorado", "population": 478961, "cityType": "Major City", "isCapital": False, "focus": "US Space Command, Aerospace, Cyber Security & Defense Technology"},
    {"cityName": "Raleigh", "stateOrRegion": "North Carolina", "population": 467665, "cityType": "Tech Hub", "isCapital": True, "focus": "Research Triangle Park (RTP) Software, Biotech & CleanTech"},
    {"cityName": "Miami", "stateOrRegion": "Florida", "population": 442241, "cityType": "Financial Hub", "isCapital": False, "focus": "Latin America LATAM HQs, Crypto, International Banking & Trade"},
    {"cityName": "Oakland", "stateOrRegion": "California", "population": 440646, "cityType": "Industrial & Port", "isCapital": False, "focus": "Port of Oakland Container Logistics, GreenTech & Creative Tech"},
    {"cityName": "Minneapolis", "stateOrRegion": "Minnesota", "population": 429954, "cityType": "Financial Hub", "isCapital": False, "focus": "Target/Best Buy Corporate HQs, Medical Device Tech & Banking"},
    {"cityName": "Tulsa", "stateOrRegion": "Oklahoma", "population": 413066, "cityType": "Major City", "isCapital": False, "focus": "Tulsa Remote Tech Incentive, Energy Tech & Aerospace Repair"},
    {"cityName": "Tampa", "stateOrRegion": "Florida", "population": 384959, "cityType": "Financial Hub", "isCapital": False, "focus": "Financial Shared Services, Cyber Defense & Healthcare Innovation"},
    {"cityName": "Arlington", "stateOrRegion": "Virginia", "population": 238643, "cityType": "Tech Hub", "isCapital": False, "focus": "Amazon HQ2, Pentagon Defense Contracting, GovTech & Cyber"},
    {"cityName": "Salt Lake City", "stateOrRegion": "Utah", "population": 199723, "cityType": "Tech Hub", "isCapital": True, "focus": "Silicon Slopes SaaS, Life Sciences, FinTech & Outdoor Industry"},
    {"cityName": "Kansas City", "stateOrRegion": "Missouri", "population": 508090, "cityType": "Regional Center", "isCapital": False, "focus": "AgTech, Logistics, Animal Health Corridor & Architecture"},
    {"cityName": "Mesa", "stateOrRegion": "Arizona", "population": 504258, "cityType": "Tech Hub", "isCapital": False, "focus": "Aerospace Components, Semiconductor Fabrication & Education"},
    {"cityName": "Virginia Beach", "stateOrRegion": "Virginia", "population": 459470, "cityType": "Industrial & Port", "isCapital": False, "focus": "Subsea Fiber Cable Landing Station, Defense & Maritime"},
    {"cityName": "Bakersfield", "stateOrRegion": "California", "population": 403455, "cityType": "Regional Center", "isCapital": False, "focus": "Energy Production, Agriculture & Central Valley Logistics"},
    {"cityName": "Aurora", "stateOrRegion": "Colorado", "population": 386261, "cityType": "Major City", "isCapital": False, "focus": "Anschutz Medical Campus, Aerospace & Defense Contracting"},
    {"cityName": "Anaheim", "stateOrRegion": "California", "population": 346824, "cityType": "Major City", "isCapital": False, "focus": "Hospitality Tech, Entertainment & Software"},
    {"cityName": "Corpus Christi", "stateOrRegion": "Texas", "population": 317863, "cityType": "Industrial & Port", "isCapital": False, "focus": "Petrochemical Refineries, Port Logistics & Naval Air"},
    {"cityName": "Riverside", "stateOrRegion": "California", "population": 314998, "cityType": "Regional Center", "isCapital": False, "focus": "Logistics Warehousing, Clean Air Research & Education"},
    {"cityName": "Lexington", "stateOrRegion": "Kentucky", "population": 322570, "cityType": "Regional Center", "isCapital": False, "focus": "Equine Biotech, Animal Health & Higher Education"},
    {"cityName": "Stockton", "stateOrRegion": "California", "population": 320804, "cityType": "Industrial & Port", "isCapital": False, "focus": "Inland Port Container Logistics & Agribusiness Processing"},
    {"cityName": "Anchorage", "stateOrRegion": "Alaska", "population": 291247, "cityType": "Regional Center", "isCapital": False, "focus": "Global Air Cargo Transit (Ted Stevens Hub) & Resource Energy"},
    {"cityName": "Cincinnati", "stateOrRegion": "Ohio", "population": 309317, "cityType": "Financial Hub", "isCapital": False, "focus": "Procter & Gamble Corporate, FinTech & Aviation Engines"},
    {"cityName": "St. Louis", "stateOrRegion": "Missouri", "population": 301574, "cityType": "Tech Hub", "isCapital": False, "focus": "Cortex Innovation District, Plant Science & Financial Services"},
    {"cityName": "Greensboro", "stateOrRegion": "North Carolina", "population": 299035, "cityType": "Major City", "isCapital": False, "focus": "Aviation Manufacturing (HondaJet), Supply Chain & Textiles"},
    {"cityName": "Plano", "stateOrRegion": "Texas", "population": 285494, "cityType": "Tech Hub", "isCapital": False, "focus": "Legacy West Corporate HQs (Toyota/Frito-Lay) & Telecom"},
    {"cityName": "Irvine", "stateOrRegion": "California", "population": 307670, "cityType": "Tech Hub", "isCapital": False, "focus": "Medical Devices, Video Game Software (Blizzard) & Semiconductor"},
    {"cityName": "Newark", "stateOrRegion": "New Jersey", "population": 311549, "cityType": "Industrial & Port", "isCapital": False, "focus": "Port Newark Shipping, Logistics, InsurTech & Legal"},
    {"cityName": "Durham", "stateOrRegion": "North Carolina", "population": 283506, "cityType": "Tech Hub", "isCapital": False, "focus": "Research Triangle Park Biotech, Clinical Trials & Software"},
    {"cityName": "Chula Vista", "stateOrRegion": "California", "population": 275639, "cityType": "Major City", "isCapital": False, "focus": "Cross-Border Technology Trade, Clean Energy & Healthcare"},
    {"cityName": "Orlando", "stateOrRegion": "Florida", "population": 307573, "cityType": "Tech Hub", "isCapital": False, "focus": "Simulation & Training Software, Optics/Photonics & Gaming"},
    {"cityName": "Toledo", "stateOrRegion": "Ohio", "population": 270871, "cityType": "Industrial & Port", "isCapital": False, "focus": "Glass Manufacturing, Automotive Assembly (Jeep) & Solar"},
    {"cityName": "Fort Wayne", "stateOrRegion": "Indiana", "population": 263886, "cityType": "Regional Center", "isCapital": False, "focus": "Defense Electronics, Medical Devices & Automotive Parts"},
    {"cityName": "Madison", "stateOrRegion": "Wisconsin", "population": 269840, "cityType": "Tech Hub", "isCapital": True, "focus": "Epic Systems Health Software, Biotech & State Government"},
    {"cityName": "Laredo", "stateOrRegion": "Texas", "population": 255205, "cityType": "Industrial & Port", "isCapital": False, "focus": "Number 1 US Cross-Border Trucking Port & Customs Brokerage"},
    {"cityName": "Lubbock", "stateOrRegion": "Texas", "population": 257141, "cityType": "Regional Center", "isCapital": False, "focus": "Cotton Trade, Agricultural Research & Regional Healthcare"},
    {"cityName": "Chandler", "stateOrRegion": "Arizona", "population": 275987, "cityType": "Tech Hub", "isCapital": False, "focus": "Intel Semiconductor Mega-Fab, Autonomous Tech & Wireless"},
    {"cityName": "Buffalo", "stateOrRegion": "New York", "population": 278349, "cityType": "Regional Center", "isCapital": False, "focus": "Medical Research (Roswell Park), Advanced Manufacturing & Clean Power"},
    {"cityName": "Reno", "stateOrRegion": "Nevada", "population": 264165, "cityType": "Tech Hub", "isCapital": False, "focus": "Tahoe Reno Industrial Center (Tesla Gigafactory) & Logistics"},
    {"cityName": "Glendale", "stateOrRegion": "Arizona", "population": 248325, "cityType": "Major City", "isCapital": False, "focus": "Sports Entertainment, Healthcare & Luke AFB Defense"},
    {"cityName": "Scottsdale", "stateOrRegion": "Arizona", "population": 241361, "cityType": "Financial Hub", "isCapital": False, "focus": "Software SaaS, Healthcare Operations & Financial Wealth"},
    {"cityName": "St. Petersburg", "stateOrRegion": "Florida", "population": 258308, "cityType": "Tech Hub", "isCapital": False, "focus": "Financial Wealth Management (Raymond James), Marine Tech & SaaS"},
    {"cityName": "Norfolk", "stateOrRegion": "Virginia", "population": 238005, "cityType": "Industrial & Port", "isCapital": False, "focus": "World Largest Naval Base, Container Shipping & Maritime Repair"},
    {"cityName": "Gilbert", "stateOrRegion": "Arizona", "population": 267918, "cityType": "Major City", "isCapital": False, "focus": "Biotech Sciences, Aerospace Systems & Clean Energy"},
    {"cityName": "Winston-Salem", "stateOrRegion": "North Carolina", "population": 249545, "cityType": "Tech Hub", "isCapital": False, "focus": "Wake Forest Biotech Innovation Quarter & Financial Operations"},
    {"cityName": "Boise", "stateOrRegion": "Idaho", "population": 235684, "cityType": "Tech Hub", "isCapital": True, "focus": "Micron Semiconductor HQs, Agribusiness & Software Tech"},
    {"cityName": "Spokane", "stateOrRegion": "Washington", "population": 228989, "cityType": "Regional Center", "isCapital": False, "focus": "Healthcare Education, Clean Energy & Aerospace Component Machining"},
    {"cityName": "Des Moines", "stateOrRegion": "Iowa", "population": 214133, "cityType": "Financial Hub", "isCapital": True, "focus": "Top 3 Global Insurance Center, FinTech & Agribusiness HQs"},
    {"cityName": "Tacoma", "stateOrRegion": "Washington", "population": 219346, "cityType": "Industrial & Port", "isCapital": False, "focus": "Deepwater Container Shipping Port, Forest Products & Health"},
    {"cityName": "Richmond", "stateOrRegion": "Virginia", "population": 226610, "cityType": "Financial Hub", "isCapital": True, "focus": "Federal Reserve District Bank, InsurTech, Tobacco Tech & Law"},
    {"cityName": "Huntsville", "stateOrRegion": "Alabama", "population": 215006, "cityType": "Tech Hub", "isCapital": False, "focus": "Rocket City NASA Marshall Space Center, Defense & Cyber"},
    {"cityName": "Rochester", "stateOrRegion": "New York", "population": 211328, "cityType": "Tech Hub", "isCapital": False, "focus": "Optics, Photonics & Imaging Capital (Kodak/Xerox Legacy)"},
    {"cityName": "Grand Rapids", "stateOrRegion": "Michigan", "population": 198917, "cityType": "Regional Center", "isCapital": False, "focus": "Medical Mile BioResearch, Office Furniture (Steelcase) & Auto"},
    {"cityName": "Fayetteville", "stateOrRegion": "Arkansas", "population": 93949, "cityType": "Regional Center", "isCapital": False, "focus": "Walmart / Tyson / J.B. Hunt Corporate Supply Chain Corridor"},
    {"cityName": "Peoria", "stateOrRegion": "Illinois", "population": 113150, "cityType": "Industrial & Port", "isCapital": False, "focus": "Caterpillar Heavy Machinery Engineering & Healthcare"},
    {"cityName": "Providence", "stateOrRegion": "Rhode Island", "population": 190934, "cityType": "Capital", "isCapital": True, "focus": "Design, Higher Education (Brown/RISD), Offshore Wind & Health"},
    {"cityName": "Worcester", "stateOrRegion": "Massachusetts", "population": 206518, "cityType": "Tech Hub", "isCapital": False, "focus": "Biomanufacturing, Life Sciences Park & Higher Education"},
    {"cityName": "Akron", "stateOrRegion": "Ohio", "population": 190203, "cityType": "Industrial & Port", "isCapital": False, "focus": "Polymer Innovation Center, Tire Tech R&D & Healthcare"},
    {"cityName": "Little Rock", "stateOrRegion": "Arkansas", "population": 202591, "cityType": "Capital", "isCapital": True, "focus": "FinTech Software, Healthcare Systems & Public Policy"},
    {"cityName": "Augusta", "stateOrRegion": "Georgia", "population": 202081, "cityType": "Tech Hub", "isCapital": False, "focus": "US Army Cyber Center of Excellence & Medical Health"},
    {"cityName": "Mobile", "stateOrRegion": "Alabama", "population": 187041, "cityType": "Industrial & Port", "isCapital": False, "focus": "Airbus Aircraft Final Assembly, Maritime Shipbuilding & Steel"},
    {"cityName": "Charleston", "stateOrRegion": "South Carolina", "population": 150227, "cityType": "Industrial & Port", "isCapital": False, "focus": "Boeing 787 Aircraft Assembly, Automotive (Volvo/BMW) & Port"},
    {"cityName": "Savannah", "stateOrRegion": "Georgia", "population": 147780, "cityType": "Industrial & Port", "isCapital": False, "focus": "Fastest Growing East Coast Container Port & Gulfstream Aerospace"},
    {"cityName": "Shreveport", "stateOrRegion": "Louisiana", "population": 187593, "cityType": "Regional Center", "isCapital": False, "focus": "Barksdale Air Force Cyber Defense & Healthcare"},
    {"cityName": "Davenport", "stateOrRegion": "Iowa", "population": 101724, "cityType": "Industrial & Port", "isCapital": False, "focus": "John Deere Heavy Equipment Manufacturing & Mississippi Shipping"},
    {"cityName": "Cedar Rapids", "stateOrRegion": "Iowa", "population": 137710, "cityType": "Tech Hub", "isCapital": False, "focus": "Collins Aerospace Avionics, Defense Communications & Grain Processing"},
    {"cityName": "Springfield", "stateOrRegion": "Missouri", "population": 169176, "cityType": "Regional Center", "isCapital": False, "focus": "Stainless Steel Tank Manufacturing & Logistics"},
    {"cityName": "Fargo", "stateOrRegion": "North Dakota", "population": 125990, "cityType": "Tech Hub", "isCapital": False, "focus": "Microsoft Business Applications Campus & AgTech Tech Park"},
    {"cityName": "Sioux Falls", "stateOrRegion": "South Dakota", "population": 192517, "cityType": "Financial Hub", "isCapital": False, "focus": "National Credit Card Banking HQs, Health Tech & No State Tax Business"},
    {"cityName": "Lincoln", "stateOrRegion": "Nebraska", "population": 291082, "cityType": "Capital", "isCapital": True, "focus": "Agritech Innovation, State Public Policy & Higher Education"},
    {"cityName": "Green Bay", "stateOrRegion": "Wisconsin", "population": 107395, "cityType": "Industrial & Port", "isCapital": False, "focus": "Papermaking Machinery, Logistics & Food Processing"},
    {"cityName": "Erie", "stateOrRegion": "Pennsylvania", "population": 94831, "cityType": "Industrial & Port", "isCapital": False, "focus": "Locomotive Manufacturing, Plastics & Lake Maritime Cargo"},
    {"cityName": "Scranton", "stateOrRegion": "Pennsylvania", "population": 76328, "cityType": "Regional Center", "isCapital": False, "focus": "E-Commerce Logistics Distribution & Healthcare Services"},
    {"cityName": "Albany", "stateOrRegion": "New York", "population": 99224, "cityType": "Capital", "isCapital": True, "focus": "Tech Valley Semiconductor Nanotech Complex (SUNY Poly) & State Gov"},
    {"cityName": "Allentown", "stateOrRegion": "Pennsylvania", "population": 125845, "cityType": "Industrial & Port", "isCapital": False, "focus": "Industrial Gas HQs (Air Products), Trucking Logistics & Electronics"},
    {"cityName": "Bridgeport", "stateOrRegion": "Connecticut", "population": 148654, "cityType": "Industrial & Port", "isCapital": False, "focus": "Precision Machining, Maritime Marine & Subcontracting"},
    {"cityName": "Stamford", "stateOrRegion": "Connecticut", "population": 135470, "cityType": "Financial Hub", "isCapital": False, "focus": "Financial Hedge Funds, Media Networks & Corporate HQs"},
    {"cityName": "New Haven", "stateOrRegion": "Connecticut", "population": 134023, "cityType": "Tech Hub", "isCapital": False, "focus": "Yale University Biotech Startups, Pharma & Legal"},
    {"cityName": "Hartford", "stateOrRegion": "Connecticut", "population": 121054, "cityType": "Financial Hub", "isCapital": True, "focus": "Insurance Capital of the World, Defense Aerospace (Pratt & Whitney)"},
    {"cityName": "Burlington", "stateOrRegion": "Vermont", "population": 44703, "cityType": "Tech Hub", "isCapital": False, "focus": "GLOBALFOUNDRIES Semiconductor Fab & Clean Tech"},
    {"cityName": "Portland", "stateOrRegion": "Maine", "population": 68408, "cityType": "Regional Center", "isCapital": False, "focus": "Veterinary Diagnostics (IDEXX), Commercial Fishing & FinTech"},
    {"cityName": "Manchester", "stateOrRegion": "New Hampshire", "population": 115644, "cityType": "Tech Hub", "isCapital": False, "focus": "Millyard Tech Incubator, ARMI Biofabrication & Financial Services"}
]

print("Python script written successfully...")
